site_name: Documentation
  
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  favicon: img/edumyst-favicon.png
  logo: img/edumyst-favicon.png
  palette:
    scheme: default
    primary: blue
    accent: blue
  features:
    - i18n

plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: bn
          name: বাংলা
          build: true
