site_name: Documentation
  
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: overrides
  favicon: assets/img/edumyst-favicon.png
  logo: assets/img/edumyst-favicon.png
  palette:
    scheme: default
    primary: blue
    accent: blue
  features:
    - i18n

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: bn
          name: বাংলা
          build: true
          
nav:
  - Home: index.md
  - Admin: 
    - Dashboard: admin/dashboard.md
    - Admission: admin/admission.md 
    - Student: admin/student.md 
    - Attendance: admin/attendance.md
    - Fees: admin/fees.md 
    - Boarding Management: admin/boarding_management.md 
    - Fund: admin/fund.md 
    - HRM & Payroll: admin/hrm_payroll.md 
    - Leave Management: admin/leave_management.md 
    - Notice and Uploads: admin/notice_and_uploads.md 
    - Home Work: admin/home_work.md 
    - Exam: admin/exam.md 
    - Marks & Result: admin/marks_result.md 
    - SMS & Email: admin/sms_email.md 
    - Event & News: admin/event_news.md 
    - Accounting: admin/accounting.md 
    - Academic Setup: admin/academic_setup.md 
    - Academic Cards: admin/academic_cards.md 
    - Front Office: admin/front_office.md 
    - Item Configuration: admin/item_configuration.md 
    - Purchase: admin/purchase.md 
    - Inventory: admin/inventory.md 
    - System Settings: admin/system_settings.md 
    - User Manage: admin/user_manage.md 
    - Profile: admin/profile.md 
    - Frontend Setup: admin/frontend_setup.md 
    - Software Subscription: admin/software_subscription.md 
