site_name: Documentation
  
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  favicon: img/edumyst-favicon.png
  logo: img/edumyst-favicon.png
  palette:
    scheme: default
    primary: indigo
    accent: blue